import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,randomBytes} from 'node:crypto';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {miniAppRequest,miniAppUser} from '../src/server/telegram/mini-app.mjs';
const env={TELEGRAM_BOT_TOKEN:randomBytes(32).toString('hex'),TELEGRAM_ALLOWED_USER_IDS:'123,456'};
function sign(id=123,date=String(Math.floor(Date.now()/1000))){const p=new URLSearchParams({user:JSON.stringify({id,first_name:'Fixture'}),auth_date:date});const key=createHmac('sha256','WebAppData').update(env.TELEGRAM_BOT_TOKEN).digest();const check=[...p.entries()].sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,v])=>k+'='+v).join('\n');p.set('hash',createHmac('sha256',key).update(check).digest('hex'));return p.toString();}
const id='00000000-0000-4000-8000-000000000001';
const actions=[{path:''},{path:'?filter=all'},{path:'?filter=yes'},{path:'?filter=no'},{path:'?filter=transfer'},{path:'?filter=overnight'},{path:'?search=Guest&offset=20'},{path:'?id='+id},{body:{action:'delete',id}},{body:{action:'confirm',token:'a'.repeat(32)}},{body:{action:'cancel',token:'a'.repeat(32)}}];
const deniedSource={connect(){assert.fail('Unauthenticated requests must never reach PostgreSQL');}};
const cases=[['direct browser',null],['fake unsigned user ID','user='+encodeURIComponent(JSON.stringify({id:123}))],['tampered initData',sign().replace('Fixture','Forged')],['damaged initData','%%%'],['expired initData',sign(123,String(Math.floor(Date.now()/1000)-3601))],['future initData',sign(123,String(Math.floor(Date.now()/1000)+31))],['not whitelisted',sign(789)],['duplicate signed parameter',sign()+'&user=123'],['invalid numeric user',sign('123')],['malformed auth date',sign(123,'1e9')]];
for(const [name,raw] of cases)test('Mini App security: '+name+' denied for every admin action',async()=>{for(const action of actions){const headers={'content-type':'application/json','telegram_user_id':'123','x-telegram-user-id':'123'};if(raw!==null)headers['x-telegram-init-data']=raw;const url='https://example.com/api/telegram/mini-app'+(action.path||'');const request=new Request(url,{method:action.body?'POST':'GET',headers,...(action.body?{body:JSON.stringify({...action.body,telegram_user_id:123,initData:sign()})}:{})});const response=await miniAppRequest(request,{env,source:deniedSource});assert.ok([401,403].includes(response.status));const data=await response.json();assert.deepEqual(Object.keys(data),['error']);assert.equal(response.headers.get('cache-control'),'private, no-store');}});
test('Mini App security: signed whitelist members allowed and unsigned identity overrides ignored',async()=>{for(const user of [123,456]){let accessed=0;const source={async connect(){accessed++;return {async query(sql){return sql.startsWith('SELECT count')?{rows:[{total:0,going:0,not_going:0,transfer:0,overnight:0}]}:{rows:[]};},release(){}};}};const response=await miniAppRequest(new Request('https://example.com/api/telegram/mini-app?telegram_user_id=789',{headers:{'x-telegram-init-data':sign(user),'x-telegram-user-id':'789'}}),{env,source});assert.equal(response.status,200);assert.equal(accessed,1);assert.equal((await response.json()).stats.total,0);assert.equal(miniAppUser(sign(user),env),String(user));}});
test('Mini App security: server-rendered page starts with denial copy, no dashboard or RSVP data',()=>{const require=createRequire(import.meta.url);const filename='src/components/TelegramAdmin.tsx';const source=fs.readFileSync(filename,'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText;const compiled={exports:{}};const localRequire=id=>id==='@/client/requests.mjs'?{boundedJson(){assert.fail('SSR must not request RSVP');},requestMessage(){return '';}}:require(id);new Function('require','module','exports',output)(localRequire,compiled,compiled.exports);const html=renderToStaticMarkup(React.createElement(compiled.exports.TelegramAdmin));assert.match(html,/Эта страница доступна только организаторам через Telegram./);assert.doesNotMatch(html,/Наши гости|admin-counts|admin-guests|admin-detail|admin-filters|Удалить ответ/);assert.doesNotMatch(source,/TELEGRAM_BOT_TOKEN|initDataUnsafe|@\/server/);const page=fs.readFileSync('src/app/telegram/page.tsx','utf8');assert.doesNotMatch(page,/@\/server|process\.env|rsvpDetail|transaction/);});
