"use client";
import Script from "next/script";
import {useState} from "react";
type Guest={id:string;status:"GOING"|"NOT_GOING";fields:{label:string;value:string}[]};
type Stats={total:number;going:number;not_going:number;transfer:number;overnight:number};
declare global{interface Window{Telegram?:{WebApp:{initData:string;ready:()=>void;expand:()=>void}}}}
export function TelegramAdmin(){
 const [guests,setGuests]=useState<Guest[]>([]),[stats,setStats]=useState<Stats|null>(null),[selected,setSelected]=useState<Guest|null>(null),[filter,setFilter]=useState("all"),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[confirmation,setConfirmation]=useState(""),[message,setMessage]=useState("Открой это приложение из меню бота с аккаунта организатора."),[busy,setBusy]=useState(false);
 async function api(path:string,body?:object){
  const initData=window.Telegram?.WebApp.initData;if(!initData)throw new Error("Открой приложение внутри Telegram.");
  const res=await fetch("/api/telegram/mini-app"+path,{method:body?"POST":"GET",cache:"no-store",headers:{"X-Telegram-Init-Data":initData,...(body?{"Content-Type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const data=await res.json();if(!res.ok)throw new Error(data.error);return data;
 }
 async function load(nextFilter=filter,nextOffset=offset){setBusy(true);try{const data=await api("?filter="+nextFilter+"&offset="+nextOffset);setGuests(data.guests);setStats(data.stats);setMore(data.hasMore);setFilter(nextFilter);setOffset(nextOffset);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Сервис недоступен.");}finally{setBusy(false);}}
 async function open(id:string){setBusy(true);try{const data=await api("?id="+id);setSelected(data.guest);setConfirmation("");setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Сервис недоступен.");}finally{setBusy(false);}}
 async function remove(){if(!selected)return;setBusy(true);try{const data=await api("",confirmation?{action:"confirm",token:confirmation}:{action:"delete",id:selected.id});setMessage(data.message);if(data.confirmation)setConfirmation(data.confirmation);else{setSelected(null);setConfirmation("");await load();setMessage(data.message);}}catch(error){setMessage(error instanceof Error?error.message:"Сервис недоступен.");}finally{setBusy(false);}}
 return <main className="telegram-admin"><Script src="https://telegram.org/js/telegram-web-app.js" strategy="afterInteractive" onReady={()=>{window.Telegram?.WebApp.ready();window.Telegram?.WebApp.expand();void load();}} onError={()=>setMessage("Не удалось загрузить Telegram. Открой приложение снова.")} />
 <header><p className="quiet-note">Anya & Maxim · Для организаторов</p><h1>Наши гости</h1></header>
 {stats&&<p className="admin-counts">Ответов {stats.total} · Придут {stats.going} · Не придут {stats.not_going}<br/>Трансфер {stats.transfer} · Ночёвка {stats.overnight}</p>}
 {message&&<p role="status" className="quiet-note">{message}</p>}
 {selected?<article className="rsvp-paper admin-detail"><button className="paper-link" disabled={busy} onClick={()=>{setSelected(null);setConfirmation("");setMessage("");}}>← К списку</button><h2>{selected.fields[0].value}</h2><p>{selected.status==="GOING"?"Придёт":"Не придёт"}</p><dl>{selected.fields.slice(1).map(field=><div key={field.label}><dt>{field.label}</dt><dd>{field.value}</dd></div>)}</dl><button className="paper-link admin-delete" disabled={busy} onClick={()=>void remove()}>{confirmation?"Подтвердить удаление":"Удалить ответ"}</button>{confirmation&&<button className="paper-link" disabled={busy} onClick={()=>{setConfirmation("");setMessage("");}}>Отмена</button>}</article>:<><nav className="admin-filters" aria-label="Фильтр ответов">{[["all","Все"],["yes","Придут"],["no","Не придут"],["transfer","Трансфер"],["overnight","Ночёвка"]].map(([value,label])=><button className="paper-link" key={value} aria-pressed={filter===value} disabled={busy} onClick={()=>void load(value,0)}>{label}</button>)}</nav><div className="admin-guests">{guests.map(guest=><button key={guest.id} onClick={()=>void open(guest.id)} disabled={busy}><span>{guest.fields[0].value}</span><small>{guest.status==="GOING"?"Придёт":"Не придёт"}</small>{guest.fields.find(field=>field.label==="Музыка")&&<small className="admin-music">Музыка: {guest.fields.find(field=>field.label==="Музыка")?.value}</small>}</button>)}</div>{stats&&guests.length===0&&<p className="quiet-note">Пока нет ответов.</p>}<div className="admin-filters">{offset>0&&<button className="paper-link" disabled={busy} onClick={()=>void load(filter,offset-20)}>Назад</button>}{more&&<button className="paper-link" disabled={busy} onClick={()=>void load(filter,offset+20)}>Дальше</button>}<button className="paper-link" disabled={busy} onClick={()=>void load()}>Обновить</button></div></>}
 </main>;
}
